TABLE--->  EMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPT_NO)

SELECT ENAME FROM EMP WHERE JOB NOT LIKE 'Manager';

SELECT  ENAME FROM EMP WHERE ENAME LIKE '-i';

SELECT COUNT(ENAME) "TOTAL_NO_OF_MANAGER" FROM EMP WHERE JOB LIKE 'Manager';

SELECT MAX(SAL) "MAXIMUM",MIN(SAL) "MINIMUM",AVG(SAL) "AVERAGE" FROM EMP;

SELECT JOB,MAX(SAL) "MAXIMUM",MIN(SAL) "MINIMUM",AVG(SAL) "AVERAGE" FROM EMP GROUP BY JOB;

SELECT * FROM EMP where HIREDATE>'01-JAN-1980';

SELECT ENAME FROM EMP WHERE JOB LIKE 'Salesman' AND SAL=(SELECT MAX(SAL) FROM EMP WHERE JOB LIKE 'Salesman');

SELECT ENAME FROM EMP WHERE JOB LIKE 'Clerk' AND SAL=(SELECT MIN(SAL) FROM EMP WHERE JOB LIKE 'Clerk');

SELECT ENAME FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME LIKE 'Turner');

SELECT JOB FROM EMP WHERE ENAME LIKE 'Ford';

SELECT JOB FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP);


DUAL:

SELECT 2+5,2*3 FROM DUAL;

SELECT SYSDATE,CURRENT_TIMESTAMP FROM DUAL;

SELECT UPPER('Aniket') FROM DUAL;

SELECT SUBSTR('Aniket') FROM DUAL;

SELECT SYSDATE-1,SYSDATE,SYSDATE+1 FROM DUAL;

SELECT SYSDATE('mm'),SYSDATE('yy') FROM DUAL;

SELECT EXTRACT(MONTH FROM SYSDATE),EXTRACT(YEAR FROM SYSDATE) FROM DUAL;

SELECT SIN(45),COS(90),TAN(0),ACOS(.20),ASIN(.20) FROM DUAL;

SELECT CEIL(3.2),FLOOR(4.9),ABS(-90),DBMS_RANDOM.RANDOM FROM DUAL;

SELECT SQRT(5) FROM DUAL;

SELECT LOWER('IVAN BAYROSS') FROM DUAL;

SELECT UPPER('IVAN BAYROSS') FROM DUAL;

SELECT TO_CHAR(SYSDATE,’DD/MM/YYYY’) "Converted" FROM DUAL;

SELECT MONTHS_BETWEEN (TO_DATE('02-02-1995','MM-DD-YYYY'),TO_DATE('01-01-1995','MM-DD-YYYY') ) "Months" FROM DUAL;

SELECT MONTHS_BETWEEN ('02-JUL-01','02-JAN-01') "Months" FROM DUAL;

SELECT SYSDATE+NUMTOYMINTERVAL(5,'MONTH') FROM DUAL;

SELECT ROUND(15.19,1) FROM DUAL;
