1.
UPDATE PRODUCT_MASTER SET Reorderlvl = 80 WHERE Description = 'Shirts';

2.
UPDATE PRODUCT_MASTER SET SellPrice = SellPrice * 1.01;

3.
UPDATE SALESMAN_MASTER SET YtdSales = YtdSales + 35 WHERE SalesmanNo = 'S00003';

4.
UPDATE SALES_ORDER_DETAILS SET QtyDisp = QtyOrdered WHERE ProductRate <= 1000;

5.
UPDATE CLIENT_MASTER SET Pincode = 400001 WHERE City = 'Mumbai';

6.
UPDATE PRODUCT_MASTER SET Reorderlvl = 2 * Reorderlvl;

7.
DELETE FROM SALES_ORDER WHERE OrderStatus = 'cancelled';

8.
DELETE FROM SALESMAN_MASTER;

9.
SELECT * FROM PRODUCT_MASTER WHERE QtyInHand < ReorderLvl;

10.
UPDATE EMP SET MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'Blake') WHERE ENAME IN ('Smith', 'Adam');

-------------
LAB SESSION-6
-------------

CREATE TABLE CUSTOMERS_2(
CUSTOMERID NUMBER(1) PRIMARY KEY,
CUSTOMERNAME VARCHAR2(20),
CONTACTNAME VARCHAR2(20),
ADDRESS VARCHAR2(30),
CITY VARCHAR2(10),
POSTALCODE VARCHAR2(5),
COUNTRY VARCHAR2(10));

CREATE TABLE SUPPLIERS(
SUPPLIERID NUMBER(1) PRIMARY KEY,
SUPPLIERNAME VARCHAR2(30),
CONTACTNAME VARCHAR2(20),
ADDRESS VARCHAR2(30),
CITY VARCHAR2(10),
POSTALCODE VARCHAR2(5),
COUNTRY VARCHAR2(10));

INSERT INTO CUSTOMERS_2 VALUES(1, 'Alfreds Futter', 'Maria Anders', 'Obere Str.57', 'Berlin', '12209', 'Germany');
INSERT INTO CUSTOMERS_2 VALUES(2, 'Ana Helados', 'Ana Trujillo', 'Avda. Construction 222', 'Mexico', '05021', 'Mexico');
INSERT INTO CUSTOMERS_2 VALUES(3, 'Antonio Moreno', 'Antonio Moreno', 'Mataderos 2312', 'Mexico', '05023', 'Mexico');

INSERT INTO SUPPLIERS VALUES(1, 'Exotic Liquid', 'Charolette Cooper', '49 GilbertSt.', 'Berlin', '12209', 'Germany');
INSERT INTO SUPPLIERS VALUES(2, 'New Orleans Cajun Delights', 'Shelley Burke', 'P.O. Box 78934', 'Mexico D.F', '05023', 'Mexico');
INSERT INTO SUPPLIERS VALUES(3, 'Grandma Kelly''s Homestead', 'Regina Murphy', '707 Oxford Rd.', 'Ann Arbor', '48104', 'USA');

1.
SELECT CITY FROM CUSTOMERS_2 UNION SELECT DISTINCT CITY FROM SUPPLIERS;

2.
SELECT CITY FROM CUSTOMERS_2 UNION ALL SELECT DISTINCT CITY FROM SUPPLIERS;

3.
SELECT CITY FROM CUSTOMERS_2 WHERE COUNTRY = 'Germany' UNION SELECT DISTINCT CITY FROM SUPPLIERS WHERE COUNTRY = 'Germany';

4.
SELECT C.CUSTOMERNAME, S.SUPPLIERNAME, S.CITY FROM CUSTOMERS_2 C, SUPPLIERS S WHERE C.CITY IN (SELECT CITY FROM SUPPLIERS INTERSECT SELECT CITY FROM CUSTOMERS_2) AND S.CITY IN(SELECT CITY FROM SUPPLIERS INTERSECT SELECT CITY FROM CUSTOMERS_2);

5.
SELECT COUNTRY FROM SUPPLIERS WHERE COUNTRY IN(SELECT COUNTRY FROM SUPPLIERS MINUS SELECT COUNTRY FROM CUSTOMERS_2);
